# IMU Serial Reader Configuration
imu_serial_reader:
  ros__parameters:
    serial_port: "/dev/ttyACM0"
    baudrate: 115200
    frame_id: "imu_link"
    publish_rate: 50.0

# IMU TF Broadcaster Configuration  
imu_tf_broadcaster:
  ros__parameters:
    base_frame: "base_link"
    imu_frame: "imu_link"
